# Use the same base image as your main Dockerfile
FROM python:3.10-slim

WORKDIR /backend

# Set the Python path
ENV PYTHONPATH=/backend

# Install pip requirements
COPY requirements.txt /backend/
RUN python -m pip install -r requirements.txt

# Copy your project files
COPY . /backend/

# Run migrations
CMD ["python", "manage.py", "migrate"]
