# Generated by Django 4.2.7 on 2023-11-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('processing_time', models.PositiveIntegerField()),
                ('amount_crafted', models.PositiveIntegerField()),
                ('crafting_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourcemap.craftingstation')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.ImageField(upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('obtained_from', models.TextField(blank=True, null=True)),
                ('stack_size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RessourceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RessourceNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressourcenodes', to='ressourcemap.map')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressourcenodes', to='ressourcemap.ressource')),
            ],
        ),
        migrations.AddField(
            model_name='ressource',
            name='ressource_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourcemap.ressourcecategory'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='used_in',
            field=models.ManyToManyField(through='ressourcemap.RecipeIngredient', to='ressourcemap.recipe'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourcemap.ressource'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourcemap.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_of_recipe', to='ressourcemap.ressource'),
        ),
    ]
