# Generated by Django 4.2.7 on 2023-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourcemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='used_in', through='ressourcemap.RecipeIngredient', to='ressourcemap.ressource'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='obtained_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
