# Generated by Django 4.2.7 on 2023-11-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressourcemap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressourcenode',
            old_name='ressource',
            new_name='ressource_type',
        ),
    ]
