# Generated by Django 4.2.7 on 2023-11-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressourcemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='ressource_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='ressourcemap.ressourcecategory'),
        ),
    ]
