# Generated by Django 4.2.7 on 2023-11-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressourcemap', '0003_ressource_is_crafted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='ressource_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='ressourcemap.ressourcecategory'),
        ),
    ]
