# Generated by Django 4.2.7 on 2023-11-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressourcemap', '0004_alter_recipeingredient_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='amount_crafted',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='icon',
        ),
        migrations.AddField(
            model_name='recipe',
            name='processing_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressourcemap.ressource'),
        ),
    ]
