# Generated by Django 4.2.7 on 2023-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressourcemap', '0005_remove_recipe_amount_crafted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amount_crafted',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='processing_time',
            field=models.PositiveIntegerField(),
        ),
    ]
